version: '1.0'
name: pipeline-20230703
displayName: 自动化部署个人博客页面到阿里云服务器
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - main
variables:
  blog_project_path: /var/webProjects/my-blog
stages:
  - name: stage-f92548b8
    displayName: 自动化部署个人博客项目
    strategy: naturally
    trigger: auto
    executor:
      - ly610126107
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 17.8.0
        commands:
          - cd /var/webProjects/my-blog
          - ''
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm install && npm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./src/.vuepress/dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
