version: '1.0'
name: pipeline-20230703
displayName: 自动化部署个人博客页面到阿里云服务器
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - main
variables:
  blog_project_path: /var/webProjects/my-blog
stages:
  - name: stage-e743b022
    displayName: nodejs编译
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 17.8.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm install && npm run docs:build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./src/vuepress/dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
  - name: stage-e54954f6
    displayName: 项目打包上传
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID:
          ID: ali-cloud
          hostID:
            - 72fbc659-237f-4f9a-acf2-f14d1c3f7a36
        deployArtifact:
          - source: build
            name: output
            target: ~/gitee_go/deploy
            dependArtifact: BUILD_ARTIFACT
        script:
          - '# 功能：部署脚本会在部署主机组的每台机器上执行'
          - '# 使用场景：先将制品包解压缩到指定目录中，再执行启动脚本deploy.sh，脚本示例地址：https://gitee.com/gitee-go/spring-boot-maven-deploy-case/blob/master/deploy.sh'
          - tar zxvf ~/gitee_go/deploy/output.tar.gz -C /var/webProjects/my-blog
          - systemctl reload nginx
        notify: []
        strategy:
          retry: '0'
